/// <reference types="cypress" />

describe('applicant', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
    cy.get('#email').type(Cypress.env('username'))
    cy.get('#password').type('1234')
    cy.intercept(`${Cypress.env('api')}/users/login`).as('login')
    cy.get('#login').click()
    cy.wait('@login')
  })

  it('create', () => {
    cy.visit('http://localhost:3000/user/create')
    cy.get('h2').should('have.text', 'Crear Usuario')
    cy.get('#rut').type('15331265-6')
    cy.get('#firstName').type('Edmundo')
    cy.get('#lastName').type('Ogaz')
    cy.get('#email').type('1234@1234.cl')
    cy.get('#company').should('be.disabled')
    cy.get('#company').select('1', {force: true})
    cy.get('#profile').select('1')
    cy.get('#save').click()
    cy.get('.Toastify__toast-body > :nth-child(2)').should('have.text', 'Saved')
    cy.wait(5000)
    cy.get('#rut').clear()
    cy.get('#rut').type('15331265-6')
    cy.get('#firstName').clear()
    cy.get('#firstName').type('Edmundo')
    cy.get('#lastName').clear()
    cy.get('#lastName').type('Ogaz')
    cy.get('#email').clear()
    cy.get('#email').type('edmundo.ogaz@gmail.cl')
    cy.get('#company').should('be.disabled')
    cy.get('#company').select('2', {force: true})
    cy.get('#profile').select('2')
    cy.get('#save').click()
    cy.get('.Toastify__toast-body > :nth-child(2)').should('have.text', 'USER_EXIST')
    cy.wait(5000)
    cy.get('#rut').clear()
    cy.get('#rut').type('3838123-1')
    cy.get('#email').clear()
    cy.get('#email').type('1234@1234.cl')
    cy.get('#save').click()
    cy.get('.Toastify__toast-body > :nth-child(2)').should('have.text', 'USER_EXIST')
  })
})
