/// <reference types="cypress" />

describe('applicant test ic test', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
    cy.get('#email').type(Cypress.env('username'))
    cy.get('#password').type('1234')
    cy.intercept(`${Cypress.env('api')}/users/login`).as('login')
    cy.get('#login').click()
    cy.wait('@login')
  })

  it('ic test', () => {
    cy.visit(`http://localhost:3000/public/test/start?id=${Cypress.env('test_disc_id')}`)
    
    cy.get('#card_0 div:nth-child(1)').should('have.text', '1/28')
    cy.get('#card_0 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_0 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Entusiasta')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Rápido(a)')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Lógico(a)')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Apacible')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[0]')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[0]')
    cy.get('#card_0 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_0 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_0 div:nth-child(3) button').click()

    cy.get('#card_1 div:nth-child(1)').should('have.text', '2/28')
    cy.get('#card_1 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_1 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Cauteloso(a)')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Decidido(a)')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Receptivo(a)')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Bondadoso(a)')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[1]')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[1]')
    cy.get('#card_1 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_1 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_1 div:nth-child(3) button').click()

    cy.get('#card_2 div:nth-child(1)').should('have.text', '3/28')
    cy.get('#card_2 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_2 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Amigable')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Preciso(a)')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Franco(a)')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Tranquilo(a)')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[2]')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[2]')
    cy.get('#card_2 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_2 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_2 div:nth-child(3) button').click()

    cy.get('#card_3 div:nth-child(1)').should('have.text', '4/28')
    cy.get('#card_3 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_3 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Elocuente')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Controlado(a)')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Tolerante')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Decisivo(a)')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[3]')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[3]')
    cy.get('#card_3 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_3 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_3 div:nth-child(3) button').click()

    cy.get('#card_4 div:nth-child(1)').should('have.text', '5/28')
    cy.get('#card_4 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_4 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Atrevido(a)')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Concienzudo(a)')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Comunicativo(a)')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Moderado(a)')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[4]')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[4]')
    cy.get('#card_4 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_4 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_4 div:nth-child(3) button').click()

    cy.get('#card_5 div:nth-child(1)').should('have.text', '6/28')
    cy.get('#card_5 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_5 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Ameno(a)')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Ingenioso(a)')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Investigador(a)')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Acepta Riesgos')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[5]')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[5]')
    cy.get('#card_5 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_5 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_5 div:nth-child(3) button').click()

    cy.get('#card_6 div:nth-child(1)').should('have.text', '7/28')
    cy.get('#card_6 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_6 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Expresivo(a)')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Cuidadoso(a)')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Dominante')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Sensible')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[6]')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[6]')
    cy.get('#card_6 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_6 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_6 div:nth-child(3) button').click()

    cy.get('#card_7 div:nth-child(1)').should('have.text', '8/28')
    cy.get('#card_7 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_7 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Extrovertido(a)')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Precavido(a)')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Constante')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Impaciente')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[7]')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[7]')
    cy.get('#card_7 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_7 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_7 div:nth-child(3) button').click()

    cy.get('#card_8 div:nth-child(1)').should('have.text', '9/28')
    cy.get('#card_8 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_8 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Discreto(a)')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Complaciente')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Encantador(a)')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Insistente')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[8]')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[8]')
    cy.get('#card_8 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_8 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_8 div:nth-child(3) button').click()

    cy.get('#card_9 div:nth-child(1)').should('have.text', '10/28')
    cy.get('#card_9 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_9 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Valeroso(a)')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Anima a los demás')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Pacífico(a)')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Perfeccionista')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[9]')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[9]')
    cy.get('#card_9 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_9 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_9 div:nth-child(3) button').click()

    cy.get('#card_10 div:nth-child(1)').should('have.text', '11/28')
    cy.get('#card_10 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_10 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Reservado(a)')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Atento(a)')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Osado(a)')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Alegre')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[10]')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[10]')
    cy.get('#card_10 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_10 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_10 div:nth-child(3) button').click()

    cy.get('#card_11 div:nth-child(1)').should('have.text', '12/28')
    cy.get('#card_11 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_11 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Estimulante')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Gentil')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Perceptivo(a)')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Independiente')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[11]')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[11]')
    cy.get('#card_11 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_11 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_11 div:nth-child(3) button').click()

    cy.get('#card_12 div:nth-child(1)').should('have.text', '13/28')
    cy.get('#card_12 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_12 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Competitivo(a)')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Considerado(a)')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Alegre')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Sagaz')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[12]')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[12]')
    cy.get('#card_12 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_12 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_12 div:nth-child(3) button').click()

    cy.get('#card_13 div:nth-child(1)').should('have.text', '14/28')
    cy.get('#card_13 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_13 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Meticuloso(a)')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Obediente')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Ideas Firmes')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Alentador(a)')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[13]')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[13]')
    cy.get('#card_13 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_13 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_13 div:nth-child(3) button').click()

    cy.get('#card_14 div:nth-child(1)').should('have.text', '15/28')
    cy.get('#card_14 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_14 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Popular')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Reflexivo(a)')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Tenaz')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Calmado(a)')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[14]')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[14]')
    cy.get('#card_14 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_14 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_14 div:nth-child(3) button').click()

    cy.get('#card_15 div:nth-child(1)').should('have.text', '16/28')
    cy.get('#card_15 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_15 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Analítico(a)')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Audaz')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Leal')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Promotor(a)')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[15]')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[15]')
    cy.get('#card_15 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_15 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_15 div:nth-child(3) button').click()

    cy.get('#card_16 div:nth-child(1)').should('have.text', '17/28')
    cy.get('#card_16 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_16 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Sociable')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Paciente')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Autosuficiente')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Certero(a)')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[16]')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[16]')
    cy.get('#card_16 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_16 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_16 div:nth-child(3) button').click()

    cy.get('#card_17 div:nth-child(1)').should('have.text', '18/28')
    cy.get('#card_17 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_17 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Adaptable')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Resuelto(a)')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Prevenido(a)')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Vivaz')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[17]')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[17]')
    cy.get('#card_17 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_17 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_17 div:nth-child(3) button').click()

    cy.get('#card_18 div:nth-child(1)').should('have.text', '19/28')
    cy.get('#card_18 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_18 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Agresivo(a)')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Impuestoso(a)')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Amistoso(a)')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Discerniente')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[18]')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[18]')
    cy.get('#card_18 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_18 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_18 div:nth-child(3) button').click()

    cy.get('#card_19 div:nth-child(1)').should('have.text', '20/28')
    cy.get('#card_19 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_19 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'De trato fácil')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Compasivo(a)')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Cauto(a)')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Habla directo')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[19]')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[19]')
    cy.get('#card_19 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_19 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_19 div:nth-child(3) button').click()

    cy.get('#card_20 div:nth-child(1)').should('have.text', '21/28')
    cy.get('#card_20 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_20 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Evaluador(a)')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Generoso(a)')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Animado(a)')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Persistente')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[20]')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[20]')
    cy.get('#card_20 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_20 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_20 div:nth-child(3) button').click()

    cy.get('#card_21 div:nth-child(1)').should('have.text', '22/28')
    cy.get('#card_21 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_21 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Impulsivo(a)')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Cuida los detalles')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Enérgico(a)')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Tranquilo(a)')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[21]')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[21]')
    cy.get('#card_21 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_21 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_21 div:nth-child(3) button').click()

    cy.get('#card_22 div:nth-child(1)').should('have.text', '23/28')
    cy.get('#card_22 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_22 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Sociable')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Sistemático(a)')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Vigoroso(a)')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Tolerante')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[22]')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[22]')
    cy.get('#card_22 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_22 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_22 div:nth-child(3) button').click()

    cy.get('#card_23 div:nth-child(1)').should('have.text', '24/28')
    cy.get('#card_23 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_23 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Cautivador(a)')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Contento(a)')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Exigente')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Apegado(a) a las normas')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[23]')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[23]')
    cy.get('#card_23 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_23 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_23 div:nth-child(3) button').click()

    cy.get('#card_24 div:nth-child(1)').should('have.text', '25/28')
    cy.get('#card_24 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_24 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Le agrada discutir')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Metódico(a)')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Comedido(a)')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Desenvuelto(a)')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[24]')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[24]')
    cy.get('#card_24 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_24 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_24 div:nth-child(3) button').click()

    cy.get('#card_25 div:nth-child(1)').should('have.text', '26/28')
    cy.get('#card_25 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_25 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Jovial')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Preciso(a)')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Directo(a)')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Ecuánime')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[25]')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[25]')
    cy.get('#card_25 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_25 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_25 div:nth-child(3) button').click()

    cy.get('#card_26 div:nth-child(1)').should('have.text', '27/28')
    cy.get('#card_26 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_26 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Inquieto(a)')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Amable')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Elocuente')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Cuidadoso(a)')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[26]')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[26]')
    cy.get('#card_26 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_26 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_26 div:nth-child(3) button').click()

    cy.get('#card_27 div:nth-child(1)').should('have.text', '28/28')
    cy.get('#card_27 div:nth-child(2) th:nth-child(2)').should('have.text', '+')
    cy.get('#card_27 div:nth-child(2) th:nth-child(3)').should('have.text', '-')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(1)').should('have.text', 'Prudente')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(1)').should('have.text', 'Pionero(a)')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(2) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(1)').should('have.text', 'Espontáneo(a)')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(3) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(1)').should('have.text', 'Colaborador')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(2) input').should('have.attr', 'name').and('equal', 'mas[27]')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(4) td:nth-child(3) input').should('have.attr', 'name').and('equal', 'menos[27]')
    cy.get('#card_27 div:nth-child(3) button').should('have.text', 'Siguiente')
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(2) span').click()
    cy.get('#card_27 div:nth-child(2) tbody tr:nth-child(1) td:nth-child(3) span').click()
    cy.get('#card_27 div:nth-child(3) button').click()

    //cy.get('#button_send').should('have.text', 'ENVIAR RESPUESTAS')
  })

  
})
